Project: Private Events
mariordgez/private-event pull request #1
Opened 2021-07-16 17:32 UTC by mariordgez

The purpose of this particular project in a general way was to use Active record associations to join different models, as well as learning how to use queries in a more useful way, this project is able to accomplish these functions:
- Create and log in as a new user
- Once logged in, you can create events
- The user is able to 'attend' events created by other users
- The index and the User's show page have their listed events sorted by past and future events using two different methods (view logic and scopes)
- The event show page allows you to attend the event as well as listing the attendees for the event

This is generally speaking how this project works, I hope you like it, have a wonderful day.

2021-07-16 18:26 UTC, SajjadAhmad14 commented on app/controllers/attendees_controller.rb
> +    # @event = Event.new
Please remove commented code. It makes the whole code base unclean.

2021-07-16 18:27 UTC, SajjadAhmad14 commented on app/controllers/events_controller.rb
> +    # @event = Event.new
Please remove commented code. It makes the whole code base unclean.

2021-07-16 18:28 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] Git flow is used properly.
- [ ] README has all the steps to run the project locally.
- [ ] Project runs perfectly.
## To Improve 🙏
- [ ] Please add `yarn install` or `npm install` so that packages can be installed related to browser functionality.
- [ ] Please remove commented code from controllers and all other files.
- [x] #index action of events controller shoul have @past_events = Event.previous_events. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png).
- [x] #index action of events controller shoul have @upcoming_events = Event.upcoming_events. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png).
- [ ] #show action of users controller should have @created_events = current_user.events. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png).
- [ ] Models should have unit tests for validations and associations using Rspec. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png).
- [ ] Authentication should have integration tests using Rspec + Capybara. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png).
- [ ] Event management features have integration tests using Rspec + Capybara. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png).
# Optional
- [ ] Views should be completely separate from app logic. You can move all view-related logic to app/helpers.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-07-17 03:59 UTC, voscarmv approved these changes
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-07-17 04:17 UTC, merged